### ISSUE TITLE
问题 脚本运行一段时间后自动关闭

### ISSUE THREAD

**Issue by FuZhuTao** [ZianTT/bilibili-hyg#11]

**Comment by FuZhuTao** [comment]
大概10分钟左右

**Comment by ZianTT** [comment]
能否提供详细的截图

**Comment by ZianTT** [comment]
您好，您似乎上传图片失败了？

**Comment by FuZhuTao** [comment]
怎样才能让这个脚本出错的时候不会自动关闭（小白）

**Comment by FuZhuTao** [comment]
> 您好，您似乎上传图片失败了？

![IMG_20230717_223516](https://github.com/ZianTT/bilibili-hyg/assets/139751529/6aeb359a-92dc-46d2-9b60-fc2f3cc99f7b)

**Comment by ZianTT** [comment]
> > 您好，您似乎上传图片失败了？
> 
> ![IMG_20230717_223516](https://user-images.githubusercontent.com/139751529/253988110-6aeb359a-92dc-46d2-9b60-fc2f3cc99f7b.jpg)

看了一下，似乎是您连接show.bilibili.com域名超时导致的错误，可能是网络问题，我之前处理的错误可能不到位，感谢反馈，稍后我将更新新的版本

**Comment by FuZhuTao** [comment]
除了这个问题之外，我还尝试去测试抢另外一种票量充足的票，当我选择两个人抢票时，界面会出现
余票4张 然后票价发生变化的循环，无法正常抢票，，但是当我单个人抢票时，成功抢票

**Comment by FuZhuTao** [comment]
我是个小白，希望我对反馈对你有帮助

**Comment by ZianTT** [comment]
> 除了这个问题之外，我还尝试去测试抢另外一种票量充足的票，当我选择两个人抢票时，界面会出现 余票4张 然后票价发生变化的循环，无法正常抢票，，但是当我单个人抢票时，成功抢票

似乎也是bug好像，能截图看看吗，因为我没尝试过抢多人的，我是靠理论猜的

**Comment by ZianTT** [comment]
超时问题可能是修复了，你再下载最新版本看看

**Comment by FuZhuTao** [comment]
> 超时问题可能是修复了，你再下载最新版本看看

程序已经正常稳定运行

**Comment by ZianTT** [comment]
> > 超时问题可能是修复了，你再下载最新版本看看
> 
> 程序已经正常稳定运行

好的，另外针对多人抢票，我似乎找到bug了，你再试试看吧
