### ISSUE TITLE
API可能失效？

### ISSUE THREAD

**Issue by NorthSkybk** [ZianTT/bilibili-hyg#12]
我在晚间23点时使用了本脚本进行测试，出现：
Traceback (most recent call last):
  File "c:\Users\31363\Desktop\codes\python_projects\bilibili-hyg\main.py", line 184, in <module>
    buyer_info = get_buyer_info()
                 ^^^^^^^^^^^^^^^^
  File "c:\Users\31363\Desktop\codes\python_projects\bilibili-hyg\main.py", line 45, in get_buyer_info
    buyer_info = [buyer_infos[0]]
                  ~~~~~~~~~~~^^^
IndexError: list index out of range
后由我自行debug后发现代码：
    response = requests.get(url, headers=headers)
    buyer_infos = response.json()["data"]["list"]
    buyer_info = [buyer_infos[0]]
buyer_info 该值是一个空数组，后经我手动调用API https://show.bilibili.com/api/ticket/buyer/list 时发现list列表中为空
{
    "errno": 0,
    "errtag": 0,
    "msg": "",
    "data": {
        "max_limit": 30,
        "list": []
    }
}

**Comment by ZianTT** [comment]
这种情况应该不是api失效，而是本来就没有已经添加的购票人
我做个处理吧，虽然新版应该不存在这个问题了
如果你确定有，检查一下cookie是否正确

**Comment by ZianTT** [comment]
处理过了，可以更新一下脚本

**Comment by NorthSkybk** [comment]
感谢，不过生草的是我一运行直接进入了风控，使用前已给本项目点上了star，感谢您的脚本😊

**Comment by ZianTT** [comment]
> 感谢，不过生草的是我一运行直接进入了风控，使用前已给本项目点上了star，感谢您的脚本😊

如果是要过GeeTest验证码，这是正常现象，用脚本都得这样
如果是业务风控就奇怪了（
