### ISSUE TITLE
说准备成功了，但是都是验证已过期

### ISSUE THREAD

**Issue by ongamer-marisa** [ZianTT/bilibili-hyg#20]
用的最新的，成功了四五个都是这样
![Q_Q1BPK(%2$HX@7UCCPYYZS](https://github.com/ZianTT/bilibili-hyg/assets/139847768/5a2832f5-5e17-4492-9bda-38b525a68fa5)

**Comment by ZianTT** [comment]
阿？理论上不会是这样的，你看看cookie是否一致（PS，这里准备订单不代表抢到了

**Comment by ZianTT** [comment]
> 哦哦，我理解错了。cookie应该没问题 但是不知道为什么昨天和今天都有一个没提示抢到，但是订单里过两个小时能看到个取消的，这正常吗

有没有一种可能，你错过了抢到的提示（
建议开启easy_mode

**Comment by ZianTT** [comment]
并且建议下载最新版本，更加友好
