### ISSUE TITLE
想请教一下请求的地址是如何获取的

### ISSUE THREAD

**Issue by Arasik** [ZianTT/bilibili-hyg#24]
想请教一下请求的地址是如何获取到是“https://show.bilibili.com/api/ticket/project/get?version=134&id=”+self.project_id的，是真的手动购买之后查看network中的消息吗

**Comment by ZianTT** [comment]
不是，你点进去详情页，就能看到projectid

**Comment by Arasik** [comment]
> 不是，你点进去详情页，就能看到projectid

不不，我知道如何获取projectid，我想知道“https://show.bilibili.com/api/ticket/project/get?version=134&id=”这个地址是如何来的，你是如何知道为什么请求这个地址就能获取票的状态的，因为最近在学习网络编程相关的知识就想了解一下

**Comment by ZianTT** [comment]
> > 不是，你点进去详情页，就能看到projectid
> 
> 不不，我知道如何获取projectid，我想知道“https://show.bilibili.com/api/ticket/project/get?version=134&id=”这个地址是如何来的，你是如何知道为什么请求这个地址就能获取票的状态的，因为最近在学习网络编程相关的知识就想了解一下

这个地址倒是不需要购买，f12network就能看到

**Comment by ZianTT** [comment]
详情页就有

**Comment by Arasik** [comment]
好的感谢
