### ISSUE TITLE
[Bug] 有关risk

### ISSUE THREAD

**Issue by ZianTT** [ZianTT/bilibili-hyg#32]
### Discussed in https://github.com/ZianTT/bilibili-hyg/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **bilibaiWater** July 24, 2023</sup>
我发现函数`test_risk()`中，是用get后状态码判断是否被风控，但是那个url用get是405方法不允许，理论上会出现412吗？

另，有关BilibiliHyg的riskheader具体是什么，好像代码内只有判断和传参赋值，我没找到生成逻辑..

希望解答

（另：这应该算是“讨论”吧..？）</div>

test_risk()函数请求方法错误

**Comment by bilibaiWater** [comment]
这应该不算是issue吧..?

还有，那个testrisk里的false和true好像反了，我下载到的源码里是状态码412为false（代表无风险？）

以及创建订单里，paymoney加了个str（），啊b会报错的，应为int（）

以及mian.py里，你的config里的data换行会读入时报错，建议删除保存cookie时的'\n'，或者加一个如果line是'\n'就continue，再或者换为pkl保存

~~其实我把你的代码重构了一遍（小声），改成了纯面向对象，包括login，但是读不懂/不想读开源协议就不放了吧~~

**Comment by ZianTT** [comment]
> 以及mian.py里，你的config里的data换行会读入时报错，建议删除保存cookie时的'\n'，或者加一个如果line是'\n'就continue，再或者换为pkl保存
这个跟踪到了， #31 的问题，等待修复
> 以及创建订单里，paymoney加了个str（），啊b会报错的，应为int（）
这个会报错吗……没看懂，fromdata为什么会有类型的问题
> 还有，那个testrisk里的false和true好像反了，我下载到的源码里是状态码412为false（代表无风险？）
412代表风险未解除，所以是false，可以看后面的代码，如果true了才会改变当前风控状态

至于重构，你可以fork一份自己的仓库，commit后可以提交PR，我是很欢迎的

**Comment by ZianTT** [comment]
已在dev分支尝试修复

**Comment by bilibaiWater** [comment]
> > 以及创建订单里，paymoney加了个str（），啊b会报错的，应为int（）
> 
> 这个会报错吗……没看懂，fromdata为什么会有类型的问题


会报错的...具体前端我也不了解，但是f12可以看到是整型的话是`"key1": 123456`，而字符串是`"key2": "123456"`

阿b真的报了错，`pay_money只能为整数`，我昨天重构的时候，就因为这个一直给阿b发包，然后他给我412了（笑

至于开fork，我再研究研究吧

**Comment by ZianTT** [comment]
> > > 以及创建订单里，paymoney加了个str（），啊b会报错的，应为int（）
> > 
> > 
> > 这个会报错吗……没看懂，fromdata为什么会有类型的问题
> 
> 会报错的...具体前端我也不了解，但是f12可以看到是整型的话是`"key1": 123456`，而字符串是`"key2": "123456"`
> 
> 阿b真的报了错，`pay_money只能为整数`，我昨天重构的时候，就因为这个一直给阿b发包，然后他给我412了（笑
> 
> 至于开fork，我再研究研究吧

看来是我的问题，在dev分支修了，如果不会开fork的话你可以根据GitHub页面引导点编辑按钮会引导你开branch的
