### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by oldganger** [ZianTT/bilibili-hyg#40]
### 描述这个Bug

5d040cb0a3e04a53b2c53ca0668a4695错误代码

### 复现步骤

不清楚

### 预期操作

是运行环境问题吗

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
config.txt中最后一行的空行删除
