### ISSUE TITLE
bilibili客户端无法识别登陆二维码[Bug]: 

### ISSUE THREAD

**Issue by evelynEdison** [ZianTT/bilibili-hyg#43]
### 描述这个Bug

login.exe生成的二维码无法识别

### 复现步骤

点击login.exe,生成二维码，并用bilibili客户端扫描，一直扫描不成功

### 预期操作

正常登陆

### 截图

![bilibili](https://github.com/ZianTT/bilibili-hyg/assets/3367428/27edae4b-c677-40fa-95c2-4d4bbf2e631f)

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
尝试安装：Windows Terminal或更换字体
另外请确认你的版本为最新版

**Comment by evelynEdison** [comment]
更换字体后可以了，thanks
