### ISSUE TITLE
[Bug]: 无法登录

### ISSUE THREAD

**Issue by leekinger** [ZianTT/bilibili-hyg#50]
### 描述这个Bug

无法登录

### 复现步骤

扫码登录

### 预期操作

可正常登录

### 截图

<img width="867" alt="2" src="https://github.com/ZianTT/bilibili-hyg/assets/39828467/0ab66d07-a0d1-4b82-9204-7d3f9f04f992">

### 问题版本

main分支-Release

### 日志

```shell
开始测试Cookie状态
2024-01-08 22:09:27.467ERROR
Traceback (most recent call last):
-_main__:<module>:75 - 程序出现错误，错误信息:data
File "main.py"，line 68，in <module>
File "api.py",line 40, in -_init_
File "login.py",line 80, in login
KeyError:'data!
2024-01-08 22:09:27.474
CRITICAL
_main_-:<module>:76 -
2024-01-08 22:09:27.477
INFO
_main_-:<module>:77
按回车将继续...
错误追踪ID(可提供给开发者): 2fe96a064904d3db3dac329ela98cdd
```

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
虽然没有找到你的问题追踪id，可能没有传上来，但是我分析应该是风控所致，过两天我会进行更新

**Comment by ZianTT** [comment]
应当已经在v0.5.2解决
