### ISSUE TITLE
你抢到票了吗

### ISSUE THREAD

**Issue by jiyuanzhiguang** [ZianTT/bilibili-hyg#6]
大哥，问一下你用这个抢到过回流票吗QAq
一个没抢到，快哭了

**Comment by xuyufenfei** [comment]
但是支付界面不锁票，除非蹲在支付界面

**Comment by xuyufenfei** [comment]
不锁的，只有跳到支付平台才锁票

**Comment by ZianTT** [comment]
> 不锁的，只有跳到支付平台才锁票

收到支付token，那应该是算进入支付进程了吧？

**Comment by jiyuanzhiguang** [comment]
那个程序能抢到吗？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZianTT/bilibili-hyg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月16日(星期天) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZianTT/bilibili-hyg] 你抢到票了吗 (Issue #6)





 
不锁的，只有跳到支付平台才锁票

**Comment by xuyufenfei** [comment]
我只抢到了一张

**Comment by jiyuanzhiguang** [comment]
明明显示锁单成功，却没有订单，为啥

**Comment by ZianTT** [comment]
> 明明显示锁单成功，却没有订单，为啥

多试几次，参考 #2

**Comment by jiyuanzhiguang** [comment]
> > 大哥，问一下你用这个抢到过回流票吗QAq
> > 一个没抢到，快哭了
> 
> 我确实是抢到了，但是bw回流票似乎结束了🤔

谢谢大哥！抢到3张

**Comment by ZianTT** [comment]
> 谢谢大哥！抢到3张

恭喜，朋友也说抢到了，看来票还是有的，但是少了不少

**Comment by jiyuanzhiguang** [comment]
我可以将它以视频的形式分享到B站吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZianTT/bilibili-hyg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月17日(星期一) 凌晨0:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZianTT/bilibili-hyg] 你抢到票了吗 (Issue #6)





  
谢谢大哥！抢到3张
  
恭喜，朋友也说抢到了，看来票还是有的，但是少了不少

**Comment by ZianTT** [comment]
> 我可以将它以视频的形式分享到B站吗

可以，别忘了帮我要star（doge）
（虽然可能被官方盯上（什）
